In [1]:
import sys
PROJECT_PATH = "/home/albert/Baikal-ML/" #insert your project path
sys.path.append(f"{PROJECT_PATH}")

In [2]:
import data.config_manager as cfgm
from data.batch_generator import BatchGenerator
from nnetworks.models.config_manager import model_from_yaml
from nnetworks.models.munusep_resnet import MuNuSepResNet
from nnetworks.learning.trainers import MuNuSepTrainer
from nnetworks.learning.config import TrainerConfig

# data
name_of_dataset = "numusep_signal_small"
train_paths = cfgm.read_paths(f"/home/albert/Baikal-ML/data/configurations/{name_of_dataset}/train_paths.csv")
train_paths = train_paths[0:20] + train_paths[-20:]
test_paths = cfgm.read_paths(f"/home/albert/Baikal-ML/data/configurations/{name_of_dataset}/test_paths.csv")
test_paths = test_paths[0:5] + test_paths[-5:]
cfg = cfgm.load_cfg(f"/home/albert/Baikal-ML/data/configurations/{name_of_dataset}/cfg.yaml")
train_gen, test_gen = BatchGenerator(train_paths, cfg), BatchGenerator(test_paths, cfg)

# model
model = model_from_yaml(MuNuSepResNet, "/home/albert/Baikal-ML/nnetworks/models/configurations/munusep_resnet.yaml")

# trainer
fitter = MuNuSepTrainer(model, train_gen, test_gen, TrainerConfig())

2024-11-03 15:58:32,375 - INFO - Shuffled all file paths. Total paths: 40
2024-11-03 15:58:32,376 - INFO - Shuffled all file paths. Total paths: 10


In [3]:
fitter.train()

Epoch 1/3


2024-11-03 15:58:51,265 - INFO - #0 chunk loaded.


Train Loss FocalLoss: 0.05767115205526352 (Epoch 0, Total steps 0)
Train Loss FocalLoss: 0.0311407981495751 (Epoch 0, Total steps 100)
Train Loss FocalLoss: 0.028059162199497223 (Epoch 0, Total steps 200)
Train Loss FocalLoss: 0.028152212187057674 (Epoch 0, Total steps 300)
Train Loss FocalLoss: 0.02731361857956589 (Epoch 0, Total steps 400)
Train Metrics Accuracy: 0.949 (Epoch 0, Total steps 500)
Train Metrics Precision: 0.9393725884918638 (Epoch 0, Total steps 500)
Train Metrics Recall: 0.9505347139704634 (Epoch 0, Total steps 500)
Train Metrics TPR: 0.9505347139704634 (Epoch 0, Total steps 500)
Train Metrics FPR: 0.052308583007671154 (Epoch 0, Total steps 500)
Train Metrics AUC: 0.9874135857964289 (Epoch 0, Total steps 500)


2024-11-03 15:59:31,428 - INFO - #0 chunk loaded.
2024-11-03 15:59:56,754 - INFO - Shuffled all file paths. Total paths: 10


Test Metrics Accuracy: 0.9280973215238502 (Epoch 0, Total steps 500)
Test Metrics Precision: 0.989937440521693 (Epoch 0, Total steps 500)
Test Metrics Recall: 0.8702342421416425 (Epoch 0, Total steps 500)
Test Metrics TPR: 0.8702342421416425 (Epoch 0, Total steps 500)
Test Metrics FPR: 0.00953450900974146 (Epoch 0, Total steps 500)
Test Metrics AUC: 0.9907672784828407 (Epoch 0, Total steps 500)
Checkpoint saved: /home/albert/Baikal-ML/experiments/testing/epoch_1.pt
Epoch 2/3
Train Loss FocalLoss: 0.026102758944034576 (Epoch 1, Total steps 500)
Train Loss FocalLoss: 0.02714876166664728 (Epoch 1, Total steps 600)
Train Loss FocalLoss: 0.027166099997587723 (Epoch 1, Total steps 700)
Train Loss FocalLoss: 0.026928376572409478 (Epoch 1, Total steps 800)
Train Loss FocalLoss: 0.02679941080289312 (Epoch 1, Total steps 900)
Train Metrics Accuracy: 0.966 (Epoch 1, Total steps 1000)
Train Metrics Precision: 0.959729843815956 (Epoch 1, Total steps 1000)
Train Metrics Recall: 0.9665516009998809 (E

2024-11-03 16:00:35,083 - INFO - #0 chunk loaded.
2024-11-03 16:01:00,073 - INFO - Shuffled all file paths. Total paths: 10


Test Metrics Accuracy: 0.9543627503290293 (Epoch 1, Total steps 1000)
Test Metrics Precision: 0.9882384035945553 (Epoch 1, Total steps 1000)
Test Metrics Recall: 0.923007296066707 (Epoch 1, Total steps 1000)
Test Metrics TPR: 0.923007296066707 (Epoch 1, Total steps 1000)
Test Metrics FPR: 0.011840529793492883 (Epoch 1, Total steps 1000)
Test Metrics AUC: 0.9957473443636045 (Epoch 1, Total steps 1000)
Checkpoint saved: /home/albert/Baikal-ML/experiments/testing/epoch_2.pt
Epoch 3/3
Train Loss FocalLoss: 0.025655493140220642 (Epoch 2, Total steps 1000)
Train Loss FocalLoss: 0.02685907448061032 (Epoch 2, Total steps 1100)
Train Loss FocalLoss: 0.02694598825113608 (Epoch 2, Total steps 1200)


2024-11-03 16:01:25,524 - INFO - #1 chunk loaded.


Train Loss FocalLoss: 0.027086622588852846 (Epoch 2, Total steps 1300)
Train Loss FocalLoss: 0.026781325293059398 (Epoch 2, Total steps 1400)
Train Metrics Accuracy: 0.9677656709875384 (Epoch 2, Total steps 1500)
Train Metrics Precision: 0.9626240996690676 (Epoch 2, Total steps 1500)
Train Metrics Recall: 0.9703371815416817 (Epoch 2, Total steps 1500)
Train Metrics TPR: 0.9703371815416817 (Epoch 2, Total steps 1500)
Train Metrics FPR: 0.034595633502507585 (Epoch 2, Total steps 1500)
Train Metrics AUC: 0.993758810807234 (Epoch 2, Total steps 1500)


2024-11-03 16:01:44,531 - INFO - #0 chunk loaded.
2024-11-03 16:02:09,729 - INFO - Shuffled all file paths. Total paths: 10


Test Metrics Accuracy: 0.969380713548892 (Epoch 2, Total steps 1500)
Test Metrics Precision: 0.9782390498229571 (Epoch 2, Total steps 1500)
Test Metrics Recall: 0.9623813703439574 (Epoch 2, Total steps 1500)
Test Metrics TPR: 0.9623813703439574 (Epoch 2, Total steps 1500)
Test Metrics FPR: 0.023074990022025454 (Epoch 2, Total steps 1500)
Test Metrics AUC: 0.9961548751779535 (Epoch 2, Total steps 1500)
Checkpoint saved: /home/albert/Baikal-ML/experiments/testing/epoch_3.pt
Training completed.


In [ ]:
from nnetworks.learning.config_manager import save_cfg
save_cfg(TrainerConfig(), "./configurations/munusep_basic.yaml")

In [5]:
import torch
t = torch.rand((1,2,2))
print(t)
t.permute((1,2,0))

tensor([[[0.0885, 0.3427],
         [0.2025, 0.4914]]])


tensor([[[0.0885],
         [0.3427]],

        [[0.2025],
         [0.4914]]])

In [13]:
(torch.zeros((1,5,1))[0,:,0] + torch.ones((5)))

tensor([1., 1., 1., 1., 1.])

In [10]:
torch.ones((5)).view(1, -1, 1)

tensor([[[1.],
         [1.],
         [1.],
         [1.],
         [1.]]])