In [1]:
import sys
PROJECT_PATH = "/home/albert/Baikal-ML/" #insert your project path
sys.path.append(f"{PROJECT_PATH}")

In [ ]:
from clearml import Task

import data.config_manager as cfgm
from data.batch_generator import BatchGenerator
from nnetworks.models.config_manager import model_from_yaml
from nnetworks.learning.config_manager import yaml2trainercfg
from nnetworks.models.munusep_resnet import MuNuSepResNet
from nnetworks.learning.trainers import MuNuSepTrainer
from nnetworks.learning.config import TrainerConfig

# data
name_of_dataset = "munusep_all_small"
train_paths = cfgm.read_paths(f"/home/albert/Baikal-ML/data/configurations/{name_of_dataset}/train_paths.csv")
test_paths = cfgm.read_paths(f"/home/albert/Baikal-ML/data/configurations/{name_of_dataset}/test_paths.csv")
cfg = cfgm.load_cfg(f"/home/albert/Baikal-ML/data/configurations/{name_of_dataset}/cfg.yaml")
train_gen, test_gen = BatchGenerator(train_paths, cfg), BatchGenerator(test_paths, cfg)

# model
model = model_from_yaml(MuNuSepResNet, "/home/albert/Baikal-ML/nnetworks/models/configurations/munusep_all_resnet.yaml")


project_name = "MuNuSepAll"
task_name="03_11_24_ResNet_SmallDS_FirstTrial"
# ClearML
task = Task.init(project_name, task_name) 
# trainer
learning_cfg = yaml2trainercfg("/home/albert/Baikal-ML/nnetworks/learning/configurations/munusepall_short.yaml")
learning_cfg.experiment_path = f"/home/albert/Baikal-ML/experiments/{project_name}/{task_name}"
fitter = MuNuSepTrainer(model, 
                        train_gen, 
                        test_gen=test_gen, 
                        train_config=learning_cfg,
                        clearml_task=task)
try:
    fitter.train()
except Exception as e:
    print(e)
    task.close()

2024-11-03 23:22:16,061 - INFO - Shuffled all file paths. Total paths: 106
2024-11-03 23:22:16,062 - INFO - Shuffled all file paths. Total paths: 15


ClearML Task: created new task id=6fcec5dafd0a42d09135b1fdf83b1e3e
2024-11-03 23:22:21,281 - clearml.Task - INFO - Storing jupyter notebook directly as code
ClearML results page: https://app.clear.ml/projects/34ab15018bbd432099027156dccd5717/experiments/6fcec5dafd0a42d09135b1fdf83b1e3e/output/log


In [3]:
task.close()

In [2]:
import data.config_manager as cfgm
from data.batch_generator import BatchGenerator
from nnetworks.models.config_manager import model_from_yaml
from nnetworks.models.munusep_resnet import MuNuSepResNet
from nnetworks.learning.trainers import MuNuSepTrainer
from nnetworks.learning.config import TrainerConfig

# data
name_of_dataset = "numusep_signal_small"
train_paths = cfgm.read_paths(f"/home/albert/Baikal-ML/data/configurations/{name_of_dataset}/train_paths.csv")
train_paths = train_paths[0:20] + train_paths[-20:]
test_paths = cfgm.read_paths(f"/home/albert/Baikal-ML/data/configurations/{name_of_dataset}/test_paths.csv")
test_paths = test_paths[0:5] + test_paths[-5:]
cfg = cfgm.load_cfg(f"/home/albert/Baikal-ML/data/configurations/{name_of_dataset}/cfg.yaml")
train_gen, test_gen = BatchGenerator(train_paths, cfg), BatchGenerator(test_paths, cfg)

# model
model = model_from_yaml(MuNuSepResNet, "/home/albert/Baikal-ML/nnetworks/models/configurations/munusep_resnet.yaml")

# trainer
fitter = MuNuSepTrainer(model, train_gen, test_gen, TrainerConfig())

2024-11-03 18:17:58,801 - INFO - Shuffled all file paths. Total paths: 40
2024-11-03 18:17:58,803 - INFO - Shuffled all file paths. Total paths: 10
2024-11-03 18:18:00,208 - INFO - Initialized MuNuSepTrainer


In [3]:
fitter.train()

2024-11-03 18:18:00,219 - INFO - 
Started Epoch 0/3
2024-11-03 18:18:14,211 - INFO - #0 chunk loaded.
2024-11-03 18:18:15,043 - INFO - logged Train Loss FocalLoss
2024-11-03 18:18:15,050 - INFO - computed metrics
2024-11-03 18:18:15,051 - INFO - logged Train Metrics Accuracy
2024-11-03 18:18:15,052 - INFO - logged Train Metrics Precision
2024-11-03 18:18:15,052 - INFO - logged Train Metrics TPR
2024-11-03 18:18:15,053 - INFO - logged Train Metrics FPR
2024-11-03 18:18:15,054 - INFO - logged Train Metrics AUC
2024-11-03 18:18:21,297 - INFO - logged Train Loss FocalLoss
2024-11-03 18:18:21,331 - INFO - computed metrics
2024-11-03 18:18:21,332 - INFO - logged Train Metrics Accuracy
2024-11-03 18:18:21,333 - INFO - logged Train Metrics Precision
2024-11-03 18:18:21,334 - INFO - logged Train Metrics TPR
2024-11-03 18:18:21,335 - INFO - logged Train Metrics FPR
2024-11-03 18:18:21,336 - INFO - logged Train Metrics AUC
2024-11-03 18:18:26,985 - INFO - logged Train Loss FocalLoss
2024-11-03 18

Checkpoint saved: /home/albert/Baikal-ML/experiments/testing/checkpoints/epoch_1.pt


2024-11-03 18:19:15,531 - INFO - logged Train Loss FocalLoss
2024-11-03 18:19:15,564 - INFO - computed metrics
2024-11-03 18:19:15,566 - INFO - logged Train Metrics Accuracy
2024-11-03 18:19:15,567 - INFO - logged Train Metrics Precision
2024-11-03 18:19:15,568 - INFO - logged Train Metrics TPR
2024-11-03 18:19:15,570 - INFO - logged Train Metrics FPR
2024-11-03 18:19:15,571 - INFO - logged Train Metrics AUC
2024-11-03 18:19:20,996 - INFO - logged Train Loss FocalLoss
2024-11-03 18:19:21,054 - INFO - computed metrics
2024-11-03 18:19:21,055 - INFO - logged Train Metrics Accuracy
2024-11-03 18:19:21,056 - INFO - logged Train Metrics Precision
2024-11-03 18:19:21,057 - INFO - logged Train Metrics TPR
2024-11-03 18:19:21,059 - INFO - logged Train Metrics FPR
2024-11-03 18:19:21,060 - INFO - logged Train Metrics AUC
2024-11-03 18:19:26,431 - INFO - logged Train Loss FocalLoss
2024-11-03 18:19:26,519 - INFO - computed metrics
2024-11-03 18:19:26,521 - INFO - logged Train Metrics Accuracy
20

Checkpoint saved: /home/albert/Baikal-ML/experiments/testing/checkpoints/epoch_2.pt


2024-11-03 18:20:08,272 - INFO - logged Train Loss FocalLoss
2024-11-03 18:20:08,309 - INFO - computed metrics
2024-11-03 18:20:08,310 - INFO - logged Train Metrics Accuracy
2024-11-03 18:20:08,312 - INFO - logged Train Metrics Precision
2024-11-03 18:20:08,313 - INFO - logged Train Metrics TPR
2024-11-03 18:20:08,315 - INFO - logged Train Metrics FPR
2024-11-03 18:20:08,316 - INFO - logged Train Metrics AUC
2024-11-03 18:20:13,656 - INFO - logged Train Loss FocalLoss
2024-11-03 18:20:13,712 - INFO - computed metrics
2024-11-03 18:20:13,713 - INFO - logged Train Metrics Accuracy
2024-11-03 18:20:13,714 - INFO - logged Train Metrics Precision
2024-11-03 18:20:13,715 - INFO - logged Train Metrics TPR
2024-11-03 18:20:13,716 - INFO - logged Train Metrics FPR
2024-11-03 18:20:13,717 - INFO - logged Train Metrics AUC
2024-11-03 18:20:25,723 - INFO - #1 chunk loaded.
2024-11-03 18:20:27,347 - INFO - logged Train Loss FocalLoss
2024-11-03 18:20:27,430 - INFO - computed metrics
2024-11-03 18:2

Checkpoint saved: /home/albert/Baikal-ML/experiments/testing/checkpoints/epoch_3.pt


In [ ]:
from nnetworks.learning.config_manager import save_trainer_cfg
save_trainer_cfg(TrainerConfig(), "./configurations/munusep_basic.yaml")

In [5]:
import torch
t = torch.rand((1,2,2))
print(t)
t.permute((1,2,0))

tensor([[[0.0885, 0.3427],
         [0.2025, 0.4914]]])


tensor([[[0.0885],
         [0.3427]],

        [[0.2025],
         [0.4914]]])

In [13]:
(torch.zeros((1,5,1))[0,:,0] + torch.ones((5)))

tensor([1., 1., 1., 1., 1.])

In [10]:
torch.ones((5)).view(1, -1, 1)

tensor([[[1.],
         [1.],
         [1.],
         [1.],
         [1.]]])

In [2]:
from pathlib import Path

In [ ]:
Path("/home/albert/Baikal-ML/data/configurations/munusep_all_small/test_paths.csv").parent

PosixPath('/home/albert/Baikal-ML/data/configurations/munusep_all_small')

In [7]:
import torch

In [25]:
(torch.ones((3,5,10)).sum((0,2))/torch.ones((3,1,1)).sum((0,1)))

tensor([10., 10., 10., 10., 10.])

In [22]:
torch.ones((3,1,1)).sum(0)

tensor([[3.]])

In [15]:
(torch.ones((5))/torch.ones((5,1))).view(1, -1, 1).shape

torch.Size([1, 25, 1])

In [16]:
torch.ones((10,5,10)) - (torch.ones((5))/torch.ones((5,1))).view(1, -1, 1)

RuntimeError: The size of tensor a (5) must match the size of tensor b (25) at non-singleton dimension 1