In [1]:
from losses import BinaryFocalLoss, FocalLoss
import torch
import torch.nn.functional as F

In [2]:
N = 5

In [8]:
logits = torch.rand((N,1))
logits = torch.concat((1.-logits, logits), dim=1).float()

labels = torch.zeros((N,1), dtype=bool)
labels[:3] = True
labels = torch.concat((~labels, labels), dim=1).float()

In [9]:
logits

tensor([[0.5229, 0.4771],
        [0.7966, 0.2034],
        [0.2786, 0.7214],
        [0.5603, 0.4397],
        [0.1744, 0.8256]])

In [10]:
labels

tensor([[0., 1.],
        [0., 1.],
        [0., 1.],
        [1., 0.],
        [1., 0.]])

In [15]:
fl = FocalLoss(1,0, "mean")
fl(logits, labels)

tensor([0.4771, 0.2034, 0.7214, 0.5603, 0.1744])


tensor(0.9970)

In [16]:
torch.nn.BCELoss()(logits, labels)

tensor(0.9970)